CREATE TABLE "TRANSPACK" (
	"id"	INTEGER NOT NULL UNIQUE,
	"short_name"	INTEGER NOT NULL,
	"begin"	INTEGER NOT NULL,
	"end"	INTEGER,
	"type"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE "TRANSPACK" (
	"id"	INTEGER NOT NULL UNIQUE,
	"short_name"	INTEGER NOT NULL,
	"tile_number"	INTEGER NOT NULL,
	"type"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);